#!/bin/bash -e

host="$1"
port=${2:-22}

tmpfile='/tmp/remote.bashrc'
rcfile="$HOME/.bashrc"

# establish master connection
ssh -qNfnMS ~/.ssh/master-%r@%h:%p $host -p $port

# send our local bashrc
scp -qo ControlPath=~/.ssh/master-%r@%h:%p -P $port "$rcfile" $host:"$tmpfile"

# establish our real connection
ssh -tS ~/.ssh/master-%r@%h:%p $host -p $port "bash --rcfile '$tmpfile'; rm -f '$tmpfile'"

# close the master connection
ssh -qO exit -S ~/.ssh/master-%r@%h:%p $host -p $port &>/dev/null
